

module AbsLambda where

-- Haskell module generated by the BNF converter




newtype Ident = Ident String deriving (Eq, Ord, Show, Read)
data Expression
    = Lambda Ident Expression
    | Application Expression Expression
    | ID Ident
  deriving (Eq, Ord, Show, Read)

