module SkelLambda where

-- Haskell module generated by the BNF converter

import AbsLambda
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transIdent :: Ident -> Result
transIdent x = case x of
  Ident string -> failure x
transExpression :: Expression -> Result
transExpression x = case x of
  Lambda ident expression -> failure x
  Application expression1 expression2 -> failure x
  ID ident -> failure x

